/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cm.tsi.pi.syshotel;

import br.edu.utfpr.cm.pi.dao.DaoHospedar;
import br.edu.utfpr.cm.pi.dao.DaoReserva;
import br.edu.utfpr.cm.pi.modal.Apartamento;
import br.edu.utfpr.cm.pi.modal.Cliente;
import br.edu.utfpr.cm.pi.modal.Hospedar;
import br.edu.utfpr.cm.pi.modal.Reserva;
import br.edu.utfpr.cm.tsi.pi.sessao.Data;
import br.edu.utfpr.cm.tsi.pi.syshotel.Util.Util;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author JoaoPaulo
 */
public class JDialogCadastrarHospedagem extends javax.swing.JDialog {

    private int idReserva;

    /**
     * Creates new form JDialogCadastrarHospedagem
     */
    public JDialogCadastrarHospedagem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
//        this.idReserva = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelImagemCadHosp = new javax.swing.JLabel();
        tfCod = new javax.swing.JTextField();
        jLabelCadHospCodigo = new javax.swing.JLabel();
        jLabelCadHospApt = new javax.swing.JLabel();
        jLabelCadHospNome = new javax.swing.JLabel();
        jLabelCadHospDataEntrada = new javax.swing.JLabel();
        ftfDataEntrada = new javax.swing.JFormattedTextField();
        jLabelCadHospDataSaida = new javax.swing.JLabel();
        ftfDataSaida = new javax.swing.JFormattedTextField();
        tfNomeCli = new javax.swing.JTextField();
        tfNApt = new javax.swing.JTextField();
        jLabelCadHospImagem = new javax.swing.JLabel();
        jButtonFechar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jSeparatorCadHosped = new javax.swing.JSeparator();
        jSeparatorCadHosp = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tdReserva = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 450));
        setMinimumSize(new java.awt.Dimension(800, 450));
        setPreferredSize(new java.awt.Dimension(800, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagemCadHosp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelImagemCadHosp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagemCadHosp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/CadHospedagem.png"))); // NOI18N
        jLabelImagemCadHosp.setPreferredSize(new java.awt.Dimension(740, 80));
        getContentPane().add(jLabelImagemCadHosp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 310, 50));

        tfCod.setEditable(false);
        tfCod.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(tfCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 130, 25));

        jLabelCadHospCodigo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCadHospCodigo.setText("Código:");
        getContentPane().add(jLabelCadHospCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabelCadHospApt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCadHospApt.setText("Nº Apartamento:");
        getContentPane().add(jLabelCadHospApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 20));

        jLabelCadHospNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCadHospNome.setText("Nome Cliente:");
        getContentPane().add(jLabelCadHospNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabelCadHospDataEntrada.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCadHospDataEntrada.setText("Data Entrada:");
        getContentPane().add(jLabelCadHospDataEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        try {
            ftfDataEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfDataEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(ftfDataEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 90, 25));

        jLabelCadHospDataSaida.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCadHospDataSaida.setText("Data Saída:");
        getContentPane().add(jLabelCadHospDataSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        try {
            ftfDataSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfDataSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(ftfDataSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 90, 25));

        tfNomeCli.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfNomeCli.setToolTipText("");
        getContentPane().add(tfNomeCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 270, 25));

        tfNApt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(tfNApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 270, 25));

        jLabelCadHospImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/Hosp.png"))); // NOI18N
        getContentPane().add(jLabelCadHospImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 130, 120));

        jButtonFechar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/Close.png"))); // NOI18N
        jButtonFechar.setToolTipText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        jButtonApagar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/trash.png"))); // NOI18N
        jButtonApagar.setToolTipText("Apagar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        jButtonLimpar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/clear02.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        jButtonSalvar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/save01.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        jSeparatorCadHosped.setMaximumSize(new java.awt.Dimension(752, 5));
        jSeparatorCadHosped.setMinimumSize(new java.awt.Dimension(752, 5));
        jSeparatorCadHosped.setPreferredSize(new java.awt.Dimension(752, 5));
        getContentPane().add(jSeparatorCadHosped, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 341, 800, 1));

        jSeparatorCadHosp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jSeparatorCadHosp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 800, 1));

        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/Add.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 30, 25));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Nº Reserva");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        tdReserva.setEditable(false);
        tdReserva.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(tdReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 130, 25));

        jButton3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/Add.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 30, 25));

        setSize(new java.awt.Dimension(816, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        if (Util.imprimirConfirmacao("Deseja Sair?")) {
            dispose();
        }
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (Util.imprimirConfirmacao("Deseja Salvar?")) {
            salvar();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        if (Util.imprimirConfirmacao("Deseja Deletar?")) {
            remover();
        }
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        if (Util.imprimirConfirmacao("Deseja Limpar?")) {
            novo();
        }
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        obter();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ftfDataEntrada;
    private javax.swing.JFormattedTextField ftfDataSaida;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCadHospApt;
    private javax.swing.JLabel jLabelCadHospCodigo;
    private javax.swing.JLabel jLabelCadHospDataEntrada;
    private javax.swing.JLabel jLabelCadHospDataSaida;
    private javax.swing.JLabel jLabelCadHospImagem;
    private javax.swing.JLabel jLabelCadHospNome;
    private javax.swing.JLabel jLabelImagemCadHosp;
    private javax.swing.JSeparator jSeparatorCadHosp;
    private javax.swing.JSeparator jSeparatorCadHosped;
    private javax.swing.JTextField tdReserva;
    private javax.swing.JTextField tfCod;
    private javax.swing.JTextField tfNApt;
    private javax.swing.JTextField tfNomeCli;
    // End of variables declaration//GEN-END:variables

    private void salvar() {

        if (verificarCampos()) {
            try {
                Hospedar hosp = new Hospedar();
                if (!tfCod.getText().isEmpty()) {  //verifica se o campo Codigo esta vazio
                    hosp.setId(Integer.parseInt(tfCod.getText()));
                }
                Apartamento a = new Apartamento();
                a.setNumero(Integer.parseInt(tfNApt.getText()));
                hosp.setApartamento(a);

                hosp.setDataInicio(Util.stringParaCalendar(ftfDataEntrada.getText()));
                hosp.setDataFim(Util.stringParaCalendar(ftfDataSaida.getText()));
                Cliente c = new Cliente();
                c.setNome(tfNomeCli.getText());
                hosp.setNome(c);

                Reserva r = new Reserva();
                r.setStatus("Concluida");
                r.setId(idReserva);

                try {
                    new DaoHospedar().persistir(hosp);
                    new DaoReserva().persistir(r);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            } catch (RuntimeException ex) {
                ex.printStackTrace();
            }
            novo();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Contem campo vazio ou tipo incorreto de dado !");
        }
    }

    protected boolean verificarCampos() {
        if (!tfNomeCli.getText().trim().equals("") && !tfNomeCli.getText().trim().isEmpty()
                && !tfNApt.getText().trim().equals("") && !tfNApt.getText().trim().isEmpty()
                && !ftfDataEntrada.getText().trim().equals("") && !ftfDataEntrada.getText().trim().isEmpty()
                && !ftfDataSaida.getText().trim().equals("") && !ftfDataSaida.getText().trim().isEmpty()) {
            return true;
        }
        return false;
    }

    private void novo() {
        tfCod.setEditable(false);
        tfNomeCli.setText(null);
        tfNApt.setText(null);
        ftfDataEntrada.setText(null);
        ftfDataSaida.setText(null);
    }

    private void remover() {

        if (!tfCod.getText().isEmpty()) {
            int id = Integer.parseInt(tfCod.getText().trim());
            try {
                DaoHospedar dao = new DaoHospedar();
                dao.remover(dao.obterPorId(id));
            } catch (Exception ex) {
                ex.printStackTrace();

            }
            novo();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Nenhum registro selecionando!");
        }
    }

    private void obter() {
        JDialog dialog = new JDialogPesquisaReservas(null, true);
        Util.abrirJDialogCentralizado(dialog);

        if (Data.hash.get("reserva") == null) {
            return;
        } else {
            if (Data.hash.get("reserva") instanceof Reserva) {
                Reserva r = (Reserva) Data.hash.get("reserva");
                Data.hash.remove("reserva");
                if (r == null) {
                    return;
                }
                tfCod.setText(String.valueOf(r.getId()));
                tfNApt.setText(String.valueOf(r.getApt().getNumero()));
                tfNomeCli.setText(r.getCli().getNome());
                ftfDataEntrada.setText(Util.stringParaCalendar(ftfDataEntrada.getText()).toString());
                ftfDataSaida.setText(Util.stringParaCalendar(ftfDataSaida.getText()).toString());

            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma Reserva.");
                Data.hash.remove("reserva");
            }
        }
    }
}
