/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cm.tsi.pi.syshotel;

import br.edu.utfpr.cm.pi.conexao.TransactionUtil;
import br.edu.utfpr.cm.pi.dao.DaoEstado;
import br.edu.utfpr.cm.pi.dao.DaoMunicipio;
import br.edu.utfpr.cm.pi.modal.Estado;
import br.edu.utfpr.cm.pi.modal.Municipio;
import br.edu.utfpr.cm.tsi.pi.sessao.Data;
import br.edu.utfpr.cm.tsi.pi.syshotel.Util.Util;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 *
 * @author JoaoPaulo
 */
public class JDialogCadastrarMunicipio extends javax.swing.JDialog {

    /**
     * Creates new form JDialogCadastrarMunicipio
     */
    public JDialogCadastrarMunicipio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popularComboBoxEstado();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFechar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelMunicipio = new javax.swing.JLabel();
        jLabelCodigoMun = new javax.swing.JLabel();
        tfCod = new javax.swing.JTextField();
        tfMunicipio = new javax.swing.JTextField();
        jLabelCityImage = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btObterEstado = new javax.swing.JButton();
        lbEstado = new javax.swing.JLabel();
        btObterMunicipio = new javax.swing.JButton();
        btObter2 = new javax.swing.JButton();
        cbEstado = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(665, 280));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonFechar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/Close.png"))); // NOI18N
        jButtonFechar.setToolTipText("Fechar");
        jButtonFechar.setBorder(null);
        jButtonFechar.setMaximumSize(new java.awt.Dimension(65, 41));
        jButtonFechar.setMinimumSize(new java.awt.Dimension(65, 41));
        jButtonFechar.setPreferredSize(new java.awt.Dimension(65, 41));
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        jButtonApagar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/trash.png"))); // NOI18N
        jButtonApagar.setToolTipText("Apagar");
        jButtonApagar.setBorder(null);
        jButtonApagar.setMaximumSize(new java.awt.Dimension(65, 41));
        jButtonApagar.setMinimumSize(new java.awt.Dimension(65, 41));
        jButtonApagar.setPreferredSize(new java.awt.Dimension(65, 41));
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        jButtonLimpar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/clear02.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        jButtonLimpar.setBorder(null);
        jButtonLimpar.setPreferredSize(new java.awt.Dimension(65, 41));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        jButtonSalvar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/save01.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setBorder(null);
        jButtonSalvar.setMaximumSize(new java.awt.Dimension(65, 41));
        jButtonSalvar.setMinimumSize(new java.awt.Dimension(65, 41));
        jButtonSalvar.setPreferredSize(new java.awt.Dimension(65, 41));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jSeparator1.setMaximumSize(new java.awt.Dimension(665, 1));
        jSeparator1.setMinimumSize(new java.awt.Dimension(665, 1));
        jSeparator1.setPreferredSize(new java.awt.Dimension(665, 1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 219, 665, 1));

        jLabelMunicipio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelMunicipio.setText("Cidade");
        getContentPane().add(jLabelMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabelCodigoMun.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCodigoMun.setText("Código:");
        getContentPane().add(jLabelCodigoMun, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        tfCod.setEditable(false);
        tfCod.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(tfCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 100, 25));

        tfMunicipio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(tfMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 210, 25));

        jLabelCityImage.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCityImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/city-icon.png"))); // NOI18N
        getContentPane().add(jLabelCityImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 140, 130));

        jSeparator2.setMaximumSize(new java.awt.Dimension(740, 5));
        jSeparator2.setMinimumSize(new java.awt.Dimension(740, 5));
        jSeparator2.setPreferredSize(new java.awt.Dimension(740, 5));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/CadCidade.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 400, 50));

        btObterEstado.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btObterEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/Add.png"))); // NOI18N
        btObterEstado.setToolTipText("Pesquisar Cadastro Estado");
        btObterEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btObterEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(btObterEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 30, 25));

        lbEstado.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lbEstado.setText("Estado:");
        getContentPane().add(lbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        btObterMunicipio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btObterMunicipio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/Add.png"))); // NOI18N
        btObterMunicipio.setToolTipText("Pesquisar Cadastro Cidade");
        btObterMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btObterMunicipioActionPerformed(evt);
            }
        });
        getContentPane().add(btObterMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 30, 25));

        btObter2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btObter2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/Add.png"))); // NOI18N
        btObter2.setToolTipText("Pesquisar Cadastro Cidade");
        btObter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btObter2ActionPerformed(evt);
            }
        });
        getContentPane().add(btObter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 30, 25));

        cbEstado.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 210, 25));

        setSize(new java.awt.Dimension(681, 333));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        if (Util.imprimirConfirmacao("Deseja Sair?")) {
            dispose();
        }
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void btObterEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btObterEstadoActionPerformed
//        Util.abrirJDialogCentralizado(new JDialogPesqEstado(null, true));
        obterEstado();
        popularComboBoxEstado();
    }//GEN-LAST:event_btObterEstadoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (Util.imprimirConfirmacao("Deseja Salvar?")) {
            salvar();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        if (Util.imprimirConfirmacao("Deseja Limpar Dados?")) {
            novo();
        }
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        if (Util.imprimirConfirmacao("Deseja Deletar?")) {
            remover();
        }
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void btObterMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btObterMunicipioActionPerformed
//        Util.abrirJDialogCentralizado(new JDialogPesqMunicipio(null, true));
        obterMunicipio();
    }//GEN-LAST:event_btObterMunicipioActionPerformed

    private void btObter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btObter2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btObter2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btObter2;
    private javax.swing.JButton btObterEstado;
    private javax.swing.JButton btObterMunicipio;
    private javax.swing.JComboBox cbEstado;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCityImage;
    private javax.swing.JLabel jLabelCodigoMun;
    private javax.swing.JLabel jLabelMunicipio;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JTextField tfCod;
    private javax.swing.JTextField tfMunicipio;
    // End of variables declaration//GEN-END:variables

    private void novo() {
        tfCod.setText(null);
        tfMunicipio.setText(null);
    }

    private void salvar() {
        if (validar()) {
            Municipio municipo = new Municipio();
            municipo.setNome(tfMunicipio.getText());
            Estado estado = (Estado) cbEstado.getSelectedItem();
            municipo.setEstado(estado);
            if (!tfCod.getText().isEmpty()) {
                municipo.setId(Integer.parseInt(tfCod.getText()));
            }
            TransactionUtil.beginTransaction();
            try {
                new DaoMunicipio().persistir(municipo);
                TransactionUtil.commit();
            } catch (Exception ex) {
                TransactionUtil.rollback();
                Logger.getLogger(JDialogCadastrarCliente.class.getName()).log(Level.SEVERE, null, ex);//erro
                Util.dispayMsg("Falha inesperada ao executar");
            }
            novo();
        } else {
            Util.dispayMsg("Contem campo vazio ou tipo incorreto de dado!");
        }
    }

    private void remover() {
        if (!tfCod.getText().isEmpty()) {
            int id = Integer.parseInt(tfCod.getText());

            try {
                DaoMunicipio dao = new DaoMunicipio();
                dao.remover(dao.obterPorId(id));

            } catch (RuntimeException e) {
                Logger.getLogger(JDialogCadastrarCliente.class.getName()).log(Level.SEVERE, null, e);//erro

                Util.dispayMsg("Falha inesperada ao executar");
            }
            novo();
        } else {
            Util.dispayMsg("Nenhum registro selecionando!");
        }

    }

    private boolean validar() {
        if (!tfMunicipio.getText().isEmpty()) {
            return true;
        }
        return false;

    }

    private void obterMunicipio() {
        JDialog dialog = new JDialogPesqMunicipio(null, true);
        Util.abrirJDialogCentralizado(dialog);
        if (Data.hash.get("cidade") == null) {
            return;
        } else {
            if (Data.hash.get("cidade") instanceof Municipio) {
                Municipio city = (Municipio) Data.hash.get("cidade");
                Data.hash.remove("cidade");
                if (city == null) {
                    return;
                }
                tfCod.setText(String.valueOf(city.getId()));
                tfMunicipio.setText(city.getNome());

            } else {
                Util.dispayMsg("Selecione um Município.");
                Data.hash.remove("cidade");//limpra o conteudo do map
            }
        }
    }

    private void obterEstado() {
        JDialog dialog = new JDialogPesqEstado(null, true);
        Util.abrirJDialogCentralizado(dialog);
        if (Data.hash.get("estado") == null) {
            return;
        } else {
            if (Data.hash.get("estado") instanceof Estado) {
                Estado est = (Estado) Data.hash.get("estado");
                Data.hash.remove("estado");
                if (est == null) {
                    return;
                }
                cbEstado.setSelectedItem(est);
            } else {
                Util.dispayMsg("Selecione um Estado.");
                Data.hash.remove("estado");//limpra o conteudo do map
            }
        }
    }

    private void popularComboBoxEstado() {
        List<Estado> estados = new DaoEstado().listar();
//        cbEstado.removeAllItems();
        for (Estado estado : estados) {
            cbEstado.addItem(estado.getNome());
            cbEstado.getSelectedIndex();
        }
    }
}
