/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cm.tsi.pi.syshotel;

import br.edu.utfpr.cm.pi.dao.DaoMunicipio;
import br.edu.utfpr.cm.pi.modal.Municipio;
import br.edu.utfpr.cm.tsi.pi.sessao.Data;
import br.edu.utfpr.cm.tsi.pi.syshotel.Util.Util;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JoaoPaulo
 */
public class JDialogPesqMunicipio extends javax.swing.JDialog {

    private DefaultTableModel model;
    private String dadosMunicipio[] = new String[]{"Cod", "Nome"};
    private List<Municipio> municipios;

    /**
     * Creates new form JDialogPesqMunicipio
     */
    public JDialogPesqMunicipio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNome = new javax.swing.JTextField();
        jLabelPesProdDescr = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMunicipio = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonCadCliente = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonAtualizar1 = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 450));
        setMinimumSize(new java.awt.Dimension(800, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 210, 30));

        jLabelPesProdDescr.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelPesProdDescr.setText("Nome:");
        getContentPane().add(jLabelPesProdDescr, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        tbMunicipio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMunicipio.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbMunicipio);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 740, 160));

        jSeparator1.setMaximumSize(new java.awt.Dimension(620, 1));
        jSeparator1.setMinimumSize(new java.awt.Dimension(620, 1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, 800, 10));

        jButtonCadCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCadCliente.setToolTipText("Cadastrar Estado");
        jButtonCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 60, 40));

        jButtonLimpar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/clear02.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 65, 41));

        jButtonAtualizar1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonAtualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/update.png"))); // NOI18N
        jButtonAtualizar1.setToolTipText("Atualizar");
        jButtonAtualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jButtonFechar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/Close.png"))); // NOI18N
        jButtonFechar.setToolTipText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 60, 40));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pesquisar Município");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 330, 50));

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/PesquisarPadrao.png"))); // NOI18N
        btPesquisar.setMaximumSize(new java.awt.Dimension(30, 30));
        btPesquisar.setMinimumSize(new java.awt.Dimension(30, 30));
        btPesquisar.setPreferredSize(new java.awt.Dimension(28, 25));
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 35, 35));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadClienteActionPerformed
        Util.abrirJDialogCentralizado(new JDialogCadastrarMunicipio(null, true));
    }//GEN-LAST:event_jButtonCadClienteActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        if (Util.imprimirConfirmacao("Deseja Limpar campos?")) {
            novo();
        }
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonAtualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizar1ActionPerformed
        atualizar();
    }//GEN-LAST:event_jButtonAtualizar1ActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        if (Util.imprimirConfirmacao("Deseja Fechar?")) {
            dispose();
        }
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        obterPorNome();
    }//GEN-LAST:event_btPesquisarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton jButtonAtualizar1;
    private javax.swing.JButton jButtonCadCliente;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPesProdDescr;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbMunicipio;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables

    private void obterPorNome() {
        try {
            model = new DefaultTableModel();
            model.setColumnIdentifiers(dadosMunicipio);
            municipios = new DaoMunicipio().obterNome(tfNome.getText());
            prencherTabela();
        } catch (Exception e) {
            System.out.println("Erro ao procurar por nome!");
            novo();
        }

    }

    private void novo() {
        tfNome.setText(null);
        popularTabela();
    }

    private void popularTabela() {
        municipios = new DaoMunicipio().listar();
        model = new DefaultTableModel();
        model.setColumnIdentifiers(dadosMunicipio);
        prencherTabela();

    }

    private void prencherTabela() {
        if (municipios != null && !municipios.isEmpty()) {

            for (Municipio city : municipios) {
                model.addRow(new Object[]{city.getId(),
                    city.getNome(),});

            }
            tbMunicipio.setModel(model);
        } else {
            model = new DefaultTableModel();
            model.setColumnIdentifiers(dadosMunicipio);
            tbMunicipio.setModel(model);
        }
    }

    private void atualizar() {
        if (tbMunicipio.getSelectedRow() != -1) {
            if (Util.imprimirConfirmacao("Atualizar")) {
                int linha = tbMunicipio.getSelectedRow();
                if (linha == -1) {
                    return;
                }
                Data.hash.put("cidade", municipios.get(linha));
            }
        }

        dispose();
    }
}
