/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cm.tsi.pi.syshotel;

import br.edu.utfpr.cm.pi.dao.DaoEstado;
import br.edu.utfpr.cm.pi.dao.DaoMunicipio;
import br.edu.utfpr.cm.pi.modal.Estado;
import br.edu.utfpr.cm.tsi.pi.sessao.Data;
import br.edu.utfpr.cm.tsi.pi.syshotel.Util.Util;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JoaoPaulo
 */
public class JDialogPesqEstado extends javax.swing.JDialog {

    private DefaultTableModel model;
    private String dadosEstado[] = new String[]{"Cod", "Nome"};
    private List<Estado> estado;

    /**
     * Creates new form JDialogPesqEstado
     */
    public JDialogPesqEstado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbEstado = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jLabelPesProdDescr1 = new javax.swing.JLabel();
        jButtonAtualizar1 = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCadCliente = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 450));
        setMinimumSize(new java.awt.Dimension(800, 450));
        setPreferredSize(new java.awt.Dimension(800, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEstado.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbEstado);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 740, 170));

        jSeparator1.setMaximumSize(new java.awt.Dimension(620, 1));
        jSeparator1.setMinimumSize(new java.awt.Dimension(620, 1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, 800, 10));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pesquisar Estado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 14, 230, 50));
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 210, 30));

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/PesquisarPadrao.png"))); // NOI18N
        btPesquisar.setMaximumSize(new java.awt.Dimension(30, 30));
        btPesquisar.setMinimumSize(new java.awt.Dimension(30, 30));
        btPesquisar.setPreferredSize(new java.awt.Dimension(28, 25));
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 35, 35));

        jLabelPesProdDescr1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelPesProdDescr1.setText("Nome:");
        getContentPane().add(jLabelPesProdDescr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jButtonAtualizar1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonAtualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/update.png"))); // NOI18N
        jButtonAtualizar1.setToolTipText("Atualizar");
        jButtonAtualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jButtonLimpar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/clear02.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 65, 41));

        jButtonCadCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCadCliente.setToolTipText("Cadastrar Estado");
        jButtonCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 60, 40));

        jButtonFechar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/Close.png"))); // NOI18N
        jButtonFechar.setToolTipText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 60, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        obterPorNome();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void jButtonAtualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizar1ActionPerformed
        atualizar();
    }//GEN-LAST:event_jButtonAtualizar1ActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        if (Util.imprimirConfirmacao("Deseja Limpar campos?")) {
            novo();
        }
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadClienteActionPerformed
        Util.abrirJDialogCentralizado(new JDialogCadastrarEstado(null, true));
    }//GEN-LAST:event_jButtonCadClienteActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        if (Util.imprimirConfirmacao("Deseja Fechar?")) {
            dispose();
        }
    }//GEN-LAST:event_jButtonFecharActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton jButtonAtualizar1;
    private javax.swing.JButton jButtonCadCliente;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPesProdDescr1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbEstado;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables

    private void obterPorNome() {
        try {
            model = new DefaultTableModel();
            model.setColumnIdentifiers(dadosEstado);
            estado = new DaoEstado().obterNome(tfNome.getText());
            prencherTabela();
        } catch (Exception e) {
            System.out.println("Erro ao procurar por nome!");
            novo();
        }

    }

    private void novo() {
        tfNome.setText(null);
        popularTabela();

    }

    private void popularTabela() {
        estado = new DaoEstado().listar();
        model = new DefaultTableModel();
        model.setColumnIdentifiers(dadosEstado);
        prencherTabela();

    }

    private void prencherTabela() {
        if (estado != null && !estado.isEmpty()) {

            for (Estado es : estado) {
                model.addRow(new Object[]{es.getId(),
                    es.getNome()});

            }
            tbEstado.setModel(model);
        } else {
            model = new DefaultTableModel();
            model.setColumnIdentifiers(dadosEstado);
            tbEstado.setModel(model);
        }
    }

    private void atualizar() {

        if (tbEstado.getSelectedRow() != -1) {
            if (Util.imprimirConfirmacao("Carregar dados?")) {
                int linha = tbEstado.getSelectedRow();
                if (linha == -1) {
                    return;
                }
                Data.hash.put("estado", estado.get(linha));
            }
        }

        dispose();
    }
}
