/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cm.tsi.pi.syshotel;

import br.edu.utfpr.cm.tsi.pi.syshotel.Util.Util;
import java.awt.Dimension;
import java.awt.TextArea;

/**
 *
 * @author JoaoPaulo
 */
public class JDialogErrorConection extends javax.swing.JDialog {

    private StackTraceElement[] stack;
    private String erro;

    public JDialogErrorConection(java.awt.Frame parent, boolean modal, StackTraceElement[] stackTrace, String erroAmigavel, String mensagemUsuario) {
        super(parent, modal);
        stack = stackTrace;
        initComponents();
        jlMessage.setText(mensagemUsuario);
        this.erro = erroAmigavel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlMessage = new javax.swing.JLabel();
        tbDetalhe = new javax.swing.JToggleButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 90));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlMessage.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jlMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/gnome-panel-force-quit.png"))); // NOI18N
        jlMessage.setText(" Falha na Conexão!");
        getContentPane().add(jlMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, 180, 57));

        tbDetalhe.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbDetalhe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/details_list.png"))); // NOI18N
        tbDetalhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDetalheActionPerformed(evt);
            }
        });
        getContentPane().add(tbDetalhe, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 37, 65, 23));

        btSair.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/mail-delete.png"))); // NOI18N
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 37, 63, 23));

        setBounds(0, 0, 556, 129);
    }// </editor-fold>//GEN-END:initComponents

    private void tbDetalheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDetalheActionPerformed
        click();
    }//GEN-LAST:event_tbDetalheActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        if (Util.imprimirConfirmacao("Deseja Sair?")) {
            dispose();
        }

    }//GEN-LAST:event_btSairActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jlMessage;
    private javax.swing.JToggleButton tbDetalhe;
    // End of variables declaration//GEN-END:variables
    private TextArea textDetalhe = new TextArea();

    private void click() {
        Dimension backup = getPreferredSize();
        if (tbDetalhe.isSelected()) {
            textDetalhe.setText(null);
            textDetalhe.setSize(new Dimension(720, 400));
            textDetalhe.setLocation(30, 100);
            textDetalhe.setEditable(false);
            setSize(new Dimension(775, 550));
            if (erro != null && !"".equals(erro) && !"null".equals(erro)) {
                textDetalhe.append(erro + "\n");
            }
            for (StackTraceElement stackTraceElement : stack) {
                textDetalhe.append(stackTraceElement + "\n");
            }
            add(textDetalhe);
            setLocationRelativeTo(null);
        }
        if (!tbDetalhe.isSelected()) {
            setSize(backup);
            remove(textDetalhe);
            setLocationRelativeTo(null);
        }
    }
}
