/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cm.tsi.pi.syshotel;

import br.edu.utfpr.cm.tsi.pi.syshotel.Util.Util;
import java.awt.Dialog;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JToolBar;

/**
 *
 * @author JoaoPaulo
 */
public class JFrameHome extends javax.swing.JFrame {

    /**
     * Creates new form JFrameHome
     */
    public JFrameHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();
        btCadastrarCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btPesquisarCliente = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btCadastrarApt = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btPesquisarApt = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btHospedar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btReservar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btPesquisarProduto = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btPesquisarFornecedor = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jLabelImagemCentral = new javax.swing.JLabel();
        jPanelStatus = new javax.swing.JPanel();
        jLabelStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastros = new javax.swing.JMenu();
        jMenuItemCadCliente = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCadApartamento = new javax.swing.JMenuItem();
        jMenuItemCadHospedagem = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItemGrupoDeProduto = new javax.swing.JMenuItem();
        jMenuItemCadProduto = new javax.swing.JMenuItem();
        jMenuItemCadFornecedor = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCadMunicípio = new javax.swing.JMenuItem();
        jMenuItemCadEstado = new javax.swing.JMenuItem();
        mnuReservas = new javax.swing.JMenu();
        mnuPesquisar = new javax.swing.JMenu();
        jMenuItemPesqCliente = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPesqApartamento = new javax.swing.JMenuItem();
        jMenuItemPesqReserva = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPesqProduto = new javax.swing.JMenuItem();
        jMenuItemPesqFornecedor = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        jMenuItemRelCliente = new javax.swing.JMenuItem();
        mnuOpcao = new javax.swing.JMenu();
        jMenuItemAjudaLeiaMe = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAjudaSobre = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SysHotel");
        setMinimumSize(new java.awt.Dimension(860, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar.setRollover(true);
        jToolBar.setToolTipText("SysHotel - Sistema de Gerencia de Hotelária");
        jToolBar.setMaximumSize(new java.awt.Dimension(863, 50));
        jToolBar.setMinimumSize(new java.awt.Dimension(863, 50));
        jToolBar.setOpaque(false);
        jToolBar.setPreferredSize(new java.awt.Dimension(863, 50));
        jToolBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToolBarMouseEntered(evt);
            }
        });

        btCadastrarCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/PROJECT/client.png"))); // NOI18N
        btCadastrarCliente.setToolTipText("Cadastrar Cliente");
        btCadastrarCliente.setBorder(null);
        btCadastrarCliente.setFocusable(false);
        btCadastrarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCadastrarCliente.setMaximumSize(new java.awt.Dimension(50, 50));
        btCadastrarCliente.setMinimumSize(new java.awt.Dimension(50, 50));
        btCadastrarCliente.setPreferredSize(new java.awt.Dimension(50, 50));
        btCadastrarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCadastrarClienteMouseEntered(evt);
            }
        });
        btCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarClienteActionPerformed(evt);
            }
        });
        jToolBar.add(btCadastrarCliente);
        jToolBar.add(jSeparator1);

        btPesquisarCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/PROJECT/clientSearch.png"))); // NOI18N
        btPesquisarCliente.setToolTipText("Pesquisar Cliente");
        btPesquisarCliente.setBorder(null);
        btPesquisarCliente.setFocusable(false);
        btPesquisarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisarCliente.setMaximumSize(new java.awt.Dimension(50, 50));
        btPesquisarCliente.setMinimumSize(new java.awt.Dimension(50, 50));
        btPesquisarCliente.setPreferredSize(new java.awt.Dimension(50, 50));
        btPesquisarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPesquisarClienteMouseEntered(evt);
            }
        });
        btPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarClienteActionPerformed(evt);
            }
        });
        jToolBar.add(btPesquisarCliente);
        jToolBar.add(jSeparator2);

        btCadastrarApt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btCadastrarApt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/PROJECT/flat.png"))); // NOI18N
        btCadastrarApt.setToolTipText("Cadastrar Apartamento");
        btCadastrarApt.setBorder(null);
        btCadastrarApt.setFocusable(false);
        btCadastrarApt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCadastrarApt.setMaximumSize(new java.awt.Dimension(50, 50));
        btCadastrarApt.setMinimumSize(new java.awt.Dimension(50, 50));
        btCadastrarApt.setPreferredSize(new java.awt.Dimension(50, 50));
        btCadastrarApt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCadastrarApt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCadastrarAptMouseEntered(evt);
            }
        });
        btCadastrarApt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarAptActionPerformed(evt);
            }
        });
        jToolBar.add(btCadastrarApt);
        jToolBar.add(jSeparator3);

        btPesquisarApt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btPesquisarApt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/PROJECT/flatSearch.png"))); // NOI18N
        btPesquisarApt.setToolTipText("Pesquisar Cliente");
        btPesquisarApt.setBorder(null);
        btPesquisarApt.setFocusable(false);
        btPesquisarApt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisarApt.setMaximumSize(new java.awt.Dimension(50, 50));
        btPesquisarApt.setMinimumSize(new java.awt.Dimension(50, 50));
        btPesquisarApt.setPreferredSize(new java.awt.Dimension(50, 50));
        btPesquisarApt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisarApt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPesquisarAptMouseEntered(evt);
            }
        });
        btPesquisarApt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarAptActionPerformed(evt);
            }
        });
        jToolBar.add(btPesquisarApt);
        jToolBar.add(jSeparator4);

        btHospedar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btHospedar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/PROJECT/host.png"))); // NOI18N
        btHospedar.setToolTipText("Hospedar");
        btHospedar.setBorder(null);
        btHospedar.setFocusable(false);
        btHospedar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btHospedar.setMaximumSize(new java.awt.Dimension(50, 50));
        btHospedar.setMinimumSize(new java.awt.Dimension(50, 50));
        btHospedar.setPreferredSize(new java.awt.Dimension(50, 50));
        btHospedar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btHospedar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btHospedarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btHospedarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btHospedarMousePressed(evt);
            }
        });
        btHospedar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHospedarActionPerformed(evt);
            }
        });
        jToolBar.add(btHospedar);
        jToolBar.add(jSeparator5);

        btReservar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/PROJECT/calendar.png"))); // NOI18N
        btReservar.setToolTipText("Reservar");
        btReservar.setBorder(null);
        btReservar.setFocusable(false);
        btReservar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btReservar.setMaximumSize(new java.awt.Dimension(50, 50));
        btReservar.setMinimumSize(new java.awt.Dimension(50, 50));
        btReservar.setPreferredSize(new java.awt.Dimension(50, 50));
        btReservar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btReservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btReservarMouseEntered(evt);
            }
        });
        btReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReservarActionPerformed(evt);
            }
        });
        jToolBar.add(btReservar);
        jToolBar.add(jSeparator6);

        btPesquisarProduto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btPesquisarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/PROJECT/productSearch.png"))); // NOI18N
        btPesquisarProduto.setToolTipText("Pesquisar Produto");
        btPesquisarProduto.setBorder(null);
        btPesquisarProduto.setFocusable(false);
        btPesquisarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisarProduto.setMaximumSize(new java.awt.Dimension(50, 50));
        btPesquisarProduto.setMinimumSize(new java.awt.Dimension(50, 50));
        btPesquisarProduto.setPreferredSize(new java.awt.Dimension(50, 50));
        btPesquisarProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPesquisarProdutoMouseEntered(evt);
            }
        });
        btPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarProdutoActionPerformed(evt);
            }
        });
        jToolBar.add(btPesquisarProduto);
        jToolBar.add(jSeparator7);

        btPesquisarFornecedor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btPesquisarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/PROJECT/searchTruck.png"))); // NOI18N
        btPesquisarFornecedor.setToolTipText("Pesquisar Fornecedor");
        btPesquisarFornecedor.setBorder(null);
        btPesquisarFornecedor.setFocusable(false);
        btPesquisarFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisarFornecedor.setMaximumSize(new java.awt.Dimension(50, 50));
        btPesquisarFornecedor.setMinimumSize(new java.awt.Dimension(50, 50));
        btPesquisarFornecedor.setPreferredSize(new java.awt.Dimension(50, 50));
        btPesquisarFornecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisarFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPesquisarFornecedorMouseEntered(evt);
            }
        });
        btPesquisarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarFornecedorActionPerformed(evt);
            }
        });
        jToolBar.add(btPesquisarFornecedor);
        jToolBar.add(jSeparator8);

        getContentPane().add(jToolBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 50));

        jLabelImagemCentral.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelImagemCentral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagemCentral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/syshotel.png"))); // NOI18N
        jLabelImagemCentral.setToolTipText("SysHotel - Sistema de Gerencia de Hotelária");
        jLabelImagemCentral.setName("SysHotel - Sistema de Gerencia de Hotelária"); // NOI18N
        jLabelImagemCentral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelImagemCentralMouseEntered(evt);
            }
        });
        getContentPane().add(jLabelImagemCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 863, 423));
        jLabelImagemCentral.getAccessibleContext().setAccessibleName("SysHotel ");

        jPanelStatus.setToolTipText("SysHotel - Sistema de Gerencia de Hotelária");
        jPanelStatus.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanelStatus.setMaximumSize(new java.awt.Dimension(863, 30));
        jPanelStatus.setMinimumSize(new java.awt.Dimension(863, 30));
        jPanelStatus.setPreferredSize(new java.awt.Dimension(863, 30));
        jPanelStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelStatusMouseEntered(evt);
            }
        });
        jPanelStatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelStatus.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(102, 102, 102));
        jLabelStatus.setText("Status");
        jLabelStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelStatus.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabelStatus.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabelStatus.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanelStatus.add(jLabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 6, 340, 20));

        getContentPane().add(jPanelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 863, 30));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(863, 30));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(863, 30));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(863, 30));
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseEntered(evt);
            }
        });

        mnuCadastros.setText("Cadastros");
        mnuCadastros.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        mnuCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuCadastrosMouseEntered(evt);
            }
        });

        jMenuItemCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCadCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemCadCliente.setText("Cliente");
        jMenuItemCadCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadClienteActionPerformed(evt);
            }
        });
        mnuCadastros.add(jMenuItemCadCliente);
        mnuCadastros.add(jSeparator10);

        jMenuItemCadApartamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCadApartamento.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemCadApartamento.setText("Apartamento");
        jMenuItemCadApartamento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemCadApartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadApartamentoActionPerformed(evt);
            }
        });
        mnuCadastros.add(jMenuItemCadApartamento);

        jMenuItemCadHospedagem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCadHospedagem.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemCadHospedagem.setText("Hospedagem");
        jMenuItemCadHospedagem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemCadHospedagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadHospedagemActionPerformed(evt);
            }
        });
        mnuCadastros.add(jMenuItemCadHospedagem);
        mnuCadastros.add(jSeparator11);

        jMenuItemGrupoDeProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemGrupoDeProduto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemGrupoDeProduto.setText("Grupo de Produto");
        jMenuItemGrupoDeProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemGrupoDeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGrupoDeProdutoActionPerformed(evt);
            }
        });
        mnuCadastros.add(jMenuItemGrupoDeProduto);

        jMenuItemCadProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCadProduto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemCadProduto.setText("Produto");
        jMenuItemCadProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadProdutoActionPerformed(evt);
            }
        });
        mnuCadastros.add(jMenuItemCadProduto);

        jMenuItemCadFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCadFornecedor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemCadFornecedor.setText("Fornecedor");
        jMenuItemCadFornecedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFornecedorActionPerformed(evt);
            }
        });
        mnuCadastros.add(jMenuItemCadFornecedor);
        mnuCadastros.add(jSeparator12);

        jMenuItemCadMunicípio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCadMunicípio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemCadMunicípio.setText("Cidade");
        jMenuItemCadMunicípio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemCadMunicípio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMunicípioActionPerformed(evt);
            }
        });
        mnuCadastros.add(jMenuItemCadMunicípio);

        jMenuItemCadEstado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCadEstado.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemCadEstado.setText("Estado");
        jMenuItemCadEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemCadEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadEstadoActionPerformed(evt);
            }
        });
        mnuCadastros.add(jMenuItemCadEstado);

        jMenuBar1.add(mnuCadastros);

        mnuReservas.setText("Reservas");
        mnuReservas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        mnuReservas.setHideActionText(true);
        mnuReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuReservasMouseEntered(evt);
            }
        });
        mnuReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReservasActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuReservas);

        mnuPesquisar.setText("Pesquisar");
        mnuPesquisar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        mnuPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuPesquisarMouseEntered(evt);
            }
        });

        jMenuItemPesqCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPesqCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemPesqCliente.setText("Cliente");
        jMenuItemPesqCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemPesqCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesqClienteActionPerformed(evt);
            }
        });
        mnuPesquisar.add(jMenuItemPesqCliente);
        mnuPesquisar.add(jSeparator13);

        jMenuItemPesqApartamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPesqApartamento.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemPesqApartamento.setText("Apartamento");
        jMenuItemPesqApartamento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemPesqApartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesqApartamentoActionPerformed(evt);
            }
        });
        mnuPesquisar.add(jMenuItemPesqApartamento);

        jMenuItemPesqReserva.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPesqReserva.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemPesqReserva.setText("Reserva");
        jMenuItemPesqReserva.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemPesqReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesqReservaActionPerformed(evt);
            }
        });
        mnuPesquisar.add(jMenuItemPesqReserva);
        mnuPesquisar.add(jSeparator14);

        jMenuItemPesqProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPesqProduto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemPesqProduto.setText("Produto");
        jMenuItemPesqProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemPesqProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesqProdutoActionPerformed(evt);
            }
        });
        mnuPesquisar.add(jMenuItemPesqProduto);

        jMenuItemPesqFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPesqFornecedor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemPesqFornecedor.setText("Fornecedor");
        jMenuItemPesqFornecedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemPesqFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesqFornecedorActionPerformed(evt);
            }
        });
        mnuPesquisar.add(jMenuItemPesqFornecedor);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Estado");
        jMenuItem1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuPesquisar.add(jMenuItem1);
        mnuPesquisar.add(jSeparator18);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Município");
        jMenuItem2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuPesquisar.add(jMenuItem2);

        jMenuBar1.add(mnuPesquisar);

        mnuRelatorios.setText("Relatórios");
        mnuRelatorios.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        mnuRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuRelatoriosMouseEntered(evt);
            }
        });

        jMenuItemRelCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemRelCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemRelCliente.setText("Cliente");
        jMenuItemRelCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItemRelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelClienteActionPerformed(evt);
            }
        });
        mnuRelatorios.add(jMenuItemRelCliente);

        jMenuBar1.add(mnuRelatorios);

        mnuOpcao.setText("Opções");
        mnuOpcao.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        mnuOpcao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuOpcaoMouseEntered(evt);
            }
        });

        jMenuItemAjudaLeiaMe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAjudaLeiaMe.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemAjudaLeiaMe.setText("Ajuda?");
        jMenuItemAjudaLeiaMe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuOpcao.add(jMenuItemAjudaLeiaMe);
        mnuOpcao.add(jSeparator17);

        jMenuItemAjudaSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAjudaSobre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItemAjudaSobre.setText("Sobre o Sistema");
        jMenuItemAjudaSobre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuOpcao.add(jMenuItemAjudaSobre);

        mnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuSair.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuOpcao.add(mnuSair);

        jMenuBar1.add(mnuOpcao);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadClienteActionPerformed

        Util.abrirJDialogCentralizado(new JDialogCadastrarCliente(this, true));
    }//GEN-LAST:event_jMenuItemCadClienteActionPerformed

    private void jMenuItemCadApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadApartamentoActionPerformed

        Util.abrirJDialogCentralizado(new JDialogCadastrarApartamento(this, true));
    }//GEN-LAST:event_jMenuItemCadApartamentoActionPerformed

    private void jMenuItemCadHospedagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadHospedagemActionPerformed

        Util.abrirJDialogCentralizado(new JDialogCadastrarHospedagem(this, true));
    }//GEN-LAST:event_jMenuItemCadHospedagemActionPerformed

    private void jMenuItemGrupoDeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGrupoDeProdutoActionPerformed

        Util.abrirJDialogCentralizado(new JDialogCadastrarGrupoDeProduto(this, true));
    }//GEN-LAST:event_jMenuItemGrupoDeProdutoActionPerformed

    private void jMenuItemCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadProdutoActionPerformed

        Util.abrirJDialogCentralizado(new JDialogCadastrarProduto(this, true));
    }//GEN-LAST:event_jMenuItemCadProdutoActionPerformed

    private void jMenuItemCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFornecedorActionPerformed

        Util.abrirJDialogCentralizado(new JDialogCadastrarFornecedor(this, true));
    }//GEN-LAST:event_jMenuItemCadFornecedorActionPerformed

    private void jMenuItemCadMunicípioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMunicípioActionPerformed

        Util.abrirJDialogCentralizado(new JDialogCadastrarMunicipio(this, true));
    }//GEN-LAST:event_jMenuItemCadMunicípioActionPerformed

    private void jMenuItemCadEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadEstadoActionPerformed

        Util.abrirJDialogCentralizado(new JDialogCadastrarEstado(this, true));
    }//GEN-LAST:event_jMenuItemCadEstadoActionPerformed

    private void jMenuItemPesqClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesqClienteActionPerformed
        Util.abrirJDialogCentralizado(new JDialogPesqCliente(this, true));
    }//GEN-LAST:event_jMenuItemPesqClienteActionPerformed

    private void jMenuItemPesqApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesqApartamentoActionPerformed

        Util.abrirJDialogCentralizado(new JDialogPesquisarApartamento(this, true));
    }//GEN-LAST:event_jMenuItemPesqApartamentoActionPerformed

    private void jMenuItemPesqReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesqReservaActionPerformed

        Util.abrirJDialogCentralizado(new JDialogPesquisaReservas(this, true));
    }//GEN-LAST:event_jMenuItemPesqReservaActionPerformed

    private void jMenuItemPesqProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesqProdutoActionPerformed

        Util.abrirJDialogCentralizado(new JDialogPesquisarProduto(this, true));
    }//GEN-LAST:event_jMenuItemPesqProdutoActionPerformed

    private void jMenuItemPesqFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesqFornecedorActionPerformed

        Util.abrirJDialogCentralizado(new JDialogPesquisarFornecedor(this, true));
    }//GEN-LAST:event_jMenuItemPesqFornecedorActionPerformed

    private void jMenuItemRelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelClienteActionPerformed

        Util.abrirJDialogCentralizado(new JDialogGerarRelatorioCliente(this, true));
    }//GEN-LAST:event_jMenuItemRelClienteActionPerformed

    private void btCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarClienteActionPerformed

        Util.abrirJDialogCentralizado(new JDialogCadastrarCliente(this, true));

    }//GEN-LAST:event_btCadastrarClienteActionPerformed

    private void btPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarClienteActionPerformed

        Util.abrirJDialogCentralizado(new JDialogPesqCliente(this, true));
    }//GEN-LAST:event_btPesquisarClienteActionPerformed

    private void btCadastrarAptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarAptActionPerformed

        Util.abrirJDialogCentralizado(new JDialogCadastrarApartamento(this, true));
    }//GEN-LAST:event_btCadastrarAptActionPerformed

    private void btPesquisarAptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarAptActionPerformed

        Util.abrirJDialogCentralizado(new JDialogPesquisarApartamento(this, true));
    }//GEN-LAST:event_btPesquisarAptActionPerformed

    private void btHospedarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHospedarActionPerformed
        // TODO add your handling code here:
        Util.abrirJDialogCentralizado(new JDialogCadastrarHospedagem(this, true));
    }//GEN-LAST:event_btHospedarActionPerformed

    private void btPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarProdutoActionPerformed

        Util.abrirJDialogCentralizado(new JDialogPesquisarProduto(this, true));
    }//GEN-LAST:event_btPesquisarProdutoActionPerformed

    private void btPesquisarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarFornecedorActionPerformed

        Util.abrirJDialogCentralizado(new JDialogPesquisarFornecedor(this, true));
    }//GEN-LAST:event_btPesquisarFornecedorActionPerformed

    private void btCadastrarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastrarClienteMouseEntered

        jLabelStatus.setText(((JButton) evt.getSource()).getToolTipText());
    }//GEN-LAST:event_btCadastrarClienteMouseEntered

    private void btPesquisarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPesquisarClienteMouseEntered

        jLabelStatus.setText(((JButton) evt.getSource()).getToolTipText());
    }//GEN-LAST:event_btPesquisarClienteMouseEntered

    private void btCadastrarAptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastrarAptMouseEntered

        jLabelStatus.setText(((JButton) evt.getSource()).getToolTipText());
    }//GEN-LAST:event_btCadastrarAptMouseEntered

    private void btPesquisarAptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPesquisarAptMouseEntered

        jLabelStatus.setText(((JButton) evt.getSource()).getToolTipText());
    }//GEN-LAST:event_btPesquisarAptMouseEntered

    private void btHospedarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHospedarMousePressed
    }//GEN-LAST:event_btHospedarMousePressed

    private void btHospedarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHospedarMouseExited
    }//GEN-LAST:event_btHospedarMouseExited

    private void btHospedarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHospedarMouseEntered

        jLabelStatus.setText(((JButton) evt.getSource()).getToolTipText());
    }//GEN-LAST:event_btHospedarMouseEntered

    private void btReservarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReservarMouseEntered
        // TODO add your handling code here:
        jLabelStatus.setText(((JButton) evt.getSource()).getToolTipText());
    }//GEN-LAST:event_btReservarMouseEntered

    private void btPesquisarProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPesquisarProdutoMouseEntered

        jLabelStatus.setText(((JButton) evt.getSource()).getToolTipText());
    }//GEN-LAST:event_btPesquisarProdutoMouseEntered

    private void btPesquisarFornecedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPesquisarFornecedorMouseEntered
        // TODO add your handling code here:
        jLabelStatus.setText(((JButton) evt.getSource()).getToolTipText());
    }//GEN-LAST:event_btPesquisarFornecedorMouseEntered

    private void jLabelImagemCentralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImagemCentralMouseEntered
        // TODO add your handling code here:
        jLabelStatus.setText(((JLabel) evt.getSource()).getName());
    }//GEN-LAST:event_jLabelImagemCentralMouseEntered
    private void mnuCadastrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCadastrosMouseEntered
        jLabelStatus.setText(((JMenuItem) evt.getSource()).getText());
    }//GEN-LAST:event_mnuCadastrosMouseEntered

    private void mnuReservasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuReservasMouseEntered
        jLabelStatus.setText(((JMenuItem) evt.getSource()).getText());
    }//GEN-LAST:event_mnuReservasMouseEntered

    private void jMenuBar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseEntered

        jLabelStatus.setText(((JMenuBar) evt.getSource()).getToolTipText());
    }//GEN-LAST:event_jMenuBar1MouseEntered

    private void jToolBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToolBarMouseEntered

        jLabelStatus.setText(((JToolBar) evt.getSource()).getToolTipText());
    }//GEN-LAST:event_jToolBarMouseEntered

    private void jPanelStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStatusMouseEntered
        // apresenta o texto ToolTipText no jLabelStatus
        jLabelStatus.setText(((JPanel) evt.getSource()).getToolTipText());
    }//GEN-LAST:event_jPanelStatusMouseEntered

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        if (Util.imprimirConfirmacao("Deseja Sair")) {
            Util.sair();
        }

    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuPesquisarMouseEntered
        jLabelStatus.setText(((JMenuItem) evt.getSource()).getText());
    }//GEN-LAST:event_mnuPesquisarMouseEntered

    private void mnuRelatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuRelatoriosMouseEntered
        jLabelStatus.setText(((JMenuItem) evt.getSource()).getText());
    }//GEN-LAST:event_mnuRelatoriosMouseEntered

    private void mnuOpcaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuOpcaoMouseEntered
        jLabelStatus.setText(((JMenuItem) evt.getSource()).getText());
    }//GEN-LAST:event_mnuOpcaoMouseEntered

    private void btReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReservarActionPerformed
        Util.abrirJDialogCentralizado(new JDialogCadastrarReservas(this, true));
    }//GEN-LAST:event_btReservarActionPerformed

    private void mnuReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReservasActionPerformed
        Util.abrirJDialogCentralizado(new JDialogCadastrarReservas(this, true));
    }//GEN-LAST:event_mnuReservasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Util.abrirJDialogCentralizado(new JDialogPesqEstado(this, true));
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Util.abrirJDialogCentralizado(new JDialogPesqMunicipio(this, true));
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrameHome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarApt;
    private javax.swing.JButton btCadastrarCliente;
    private javax.swing.JButton btHospedar;
    private javax.swing.JButton btPesquisarApt;
    private javax.swing.JButton btPesquisarCliente;
    private javax.swing.JButton btPesquisarFornecedor;
    private javax.swing.JButton btPesquisarProduto;
    private javax.swing.JButton btReservar;
    private javax.swing.JLabel jLabelImagemCentral;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAjudaLeiaMe;
    private javax.swing.JMenuItem jMenuItemAjudaSobre;
    private javax.swing.JMenuItem jMenuItemCadApartamento;
    private javax.swing.JMenuItem jMenuItemCadCliente;
    private javax.swing.JMenuItem jMenuItemCadEstado;
    private javax.swing.JMenuItem jMenuItemCadFornecedor;
    private javax.swing.JMenuItem jMenuItemCadHospedagem;
    private javax.swing.JMenuItem jMenuItemCadMunicípio;
    private javax.swing.JMenuItem jMenuItemCadProduto;
    private javax.swing.JMenuItem jMenuItemGrupoDeProduto;
    private javax.swing.JMenuItem jMenuItemPesqApartamento;
    private javax.swing.JMenuItem jMenuItemPesqCliente;
    private javax.swing.JMenuItem jMenuItemPesqFornecedor;
    private javax.swing.JMenuItem jMenuItemPesqProduto;
    private javax.swing.JMenuItem jMenuItemPesqReserva;
    private javax.swing.JMenuItem jMenuItemRelCliente;
    private javax.swing.JPanel jPanelStatus;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenu mnuOpcao;
    private javax.swing.JMenu mnuPesquisar;
    private javax.swing.JMenu mnuRelatorios;
    private javax.swing.JMenu mnuReservas;
    private javax.swing.JMenuItem mnuSair;
    // End of variables declaration//GEN-END:variables
}
