/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cm.tsi.pi.syshotel;

import br.edu.utfpr.cm.pi.conexao.Conexao;
import br.edu.utfpr.cm.pi.conexao.HibernateUtil;
import br.edu.utfpr.cm.tsi.pi.syshotel.Util.Util;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Mary
 */
public class LoginNovo extends javax.swing.JFrame {

    /**
     * Creates new form LoginNovo
     */
    public LoginNovo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUser = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        btLogin = new javax.swing.JButton();
        tfPass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(355, 336));
        setMinimumSize(new java.awt.Dimension(355, 336));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfUser.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUser.setText("root");
        tfUser.setMaximumSize(new java.awt.Dimension(28, 14));
        tfUser.setMinimumSize(new java.awt.Dimension(28, 14));
        tfUser.setPreferredSize(new java.awt.Dimension(28, 14));
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });
        getContentPane().add(tfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 254, 100, 20));

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/sair_1.png"))); // NOI18N
        btSair.setToolTipText("Sair");
        btSair.setMaximumSize(new java.awt.Dimension(94, 32));
        btSair.setMinimumSize(new java.awt.Dimension(94, 32));
        btSair.setPreferredSize(new java.awt.Dimension(94, 32));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 94, 32));

        btLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/login.png"))); // NOI18N
        btLogin.setToolTipText("Login");
        btLogin.setPreferredSize(new java.awt.Dimension(97, 32));
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 97, 32));

        tfPass.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPass.setText("root");
        getContentPane().add(tfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 254, 100, 20));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/pi/icons/loginNovo.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 355, 336));

        setSize(new java.awt.Dimension(355, 366));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        if (Util.imprimirConfirmacao("Deseja Sair?")) {
            Util.sair();
        }

    }//GEN-LAST:event_btSairActionPerformed

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        try {
            criaBanco();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao iniciar aplicação.");
        }

    }//GEN-LAST:event_btLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginNovo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfPass;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables

    private void criaBanco() throws SQLException {
        String usuario = tfUser.getText();
        String senha = tfPass.getText();

        HibernateUtil.setUser(usuario);
        HibernateUtil.setPass(senha);

        Connection conexao = Conexao.getConnection();
        if (Util.imprimirConfirmacao("Já possui a base de dados ?")) {
            Util.abrirJFrameCentralizado(new JFrameHome());
            this.dispose();
        } else {
            try {
                conexao.createStatement().execute("create database if not EXISTS syshotel");
                conexao.createStatement().execute("use syshotel");
                HibernateUtil.criarSchema();
                Util.abrirJFrameCentralizado(new JFrameHome());
                this.dispose();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Problema ao criar Banco");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro inesperado ao tentar iniciar");
            }
        }

    }
}
